#ifndef __CHAT_PACKETS__
#define __CHAT_PACKETS__

#define USE_METASERVER_INITIALIZATION_PACKET
#  define SEND_METASERVER_INITIALIZATION_PACKET

#define USE_METASERVER_ASKINFO_PACKET
#  define SEND_METASERVER_ASKINFO_PACKET

#define USE_INITIALIZATION_PACKET 
#  define SEND_INITIALIZATION_PACKET 

#define USE_SUBMIT_PACKET
#  define RECV_SUBMIT_PACKET
#  define SEND_SUBMIT_PACKET

#define USE_METASERVER_DATA_PACKET
#  define RECV_METASERVER_DATA_PACKET

#define USE_COMMAND_PACKET
#  define RECV_COMMAND_PACKET
#  define SEND_COMMAND_PACKET

#define USE_CHAT_MESSAGE_PACKET
#  define SEND_CHAT_MESSAGE_PACKET

#define USE_SERVER_MESSAGE_PACKET
#  define RECV_SERVER_MESSAGE_PACKET

#include "Packets.h"

#endif
