#ifndef __METASERVER_PACKETS__
#define __METASERVER_PACKETS__


#define USE_METASERVER_INITIALIZATION_PACKET
#  define RECV_METASERVER_INITIALIZATION_PACKET

#define USE_METASERVER_ASKINFO_PACKET
#  define RECV_METASERVER_ASKINFO_PACKET

#define USE_METASERVER_DATA_PACKET
#  define RECV_METASERVER_DATA_PACKET
#  define SEND_METASERVER_DATA_PACKET

#define USE_COMMAND_PACKET
#  define SEND_COMMAND_PACKET

#include "Packets.h"

#endif
