#ifndef __SERVER_PACKET_H__
#define __SERVER_PACKET_H__

/* 
   Define the packets you need and how you gonna use them 
*/

#define USE_INITIALIZATION_PACKET
#  define RECV_INITIALIZATION_PACKET

#define USE_COMMAND_PACKET
#  define SEND_COMMAND_PACKET
#  define RECV_COMMAND_PACKET

#define USE_CHAT_MESSAGE_PACKET
#  define RECV_CHAT_MESSAGE_PACKET

#define USE_SERVER_MESSAGE_PACKET
#  define SEND_SERVER_MESSAGE_PACKET

#define USE_SUBMIT_PACKET
#  define SEND_SUBMIT_PACKET
#  define RECV_SUBMIT_PACKET

#define USE_METASERVER_INITIALIZATION_PACKET
#  define SEND_METASERVER_INITIALIZATION_PACKET

#define USE_METASERVER_DATA_PACKET
#  define SEND_METASERVER_DATA_PACKET

#define USE_METASERVER_ASKINFO_PACKET
#  define SEND_METASERVER_ASKINFO_PACKET

#include "Packets.h"

#endif
